theme: minima
title: My Awesome Blog
author: Vicente
email: vince.damien31@vdtdesigns.best
description: > # this means to ignore newlines until "baseurl:"
  Bomb hairdresser and baber.

# social links
instagram_username: VDTDesigns
github_username: Vicentefame1

show_excerpts: true # set to false to remove excerpts on the homepage
